### ISSUE TITLE
Failed slices with error Queue full from node-rdkafka

### ISSUE THREAD

**Issue by ciorg** [terascope/kafka-assets#755]
Kafka asset should guard against filling the kafka record queue, but we are seeing occasional slice failures caused by this issue in a particular job.

Slice Error:
```
TSError: AggregateError: Error: Local: Queue full at Function.createLibrdkafkaError [as create] (/app/node_modules/node-rdkafka/lib/error.js:456:10) at Client._errorWrap (/app/node_modules/node-rdkafka/lib/client.js:481:29) at Producer.produce (/app/node_modules/node-rdkafka/lib/producer.js:138:15) at ProducerClient.produce 
```

Job Details:
```json
{
    "name": "NAME",
    "lifecycle": "persistent",
    "workers": 30,
    "assets": [
        "common_processors:0.11.0",
        "general_datatypes:0.17.0",
        "standard:0.22.4",
        "kafka:3.4.0"
    ],
    "kubernetes_image": "docker.lan/teraslice:v0.93.0-nodev18.18.2",
    "resources_requests_cpu": 1,
    "resources_limits_cpu": 2,
    "resources_requests_memory": 536870912,
    "resources_limits_memory": 1610612736,
    "operations": [
        {
            "_op": "kafka_reader",
            "connection": "CONNECTION",
            "topic": "TOPIC",
            "group": "GROUP",
            "size": 100000,
            "wait": 5000
        },
        {
            "_op": "field_router",
            "fields": ["FIELD"]
        },
        {
            "_op": "routed_sender",
            "api_name": "kafka_sender_api",
            "size": 50000,
            "routing": {
                "FIELD_A": "CONNECTION_1",
                "FIELD_B": "CONNECTION_1",
                "FIELD_C": "CONNECTION_1"
            }
        }
    ],
    "apis": [
        {
            "_name": "kafka_sender_api",
            "topic": "TOPIC_NAME"
        }
    ]
}

```

**Comment by sotojn** [comment]
The error reformatted 

```
TSError: AggregateError: Error: Local: Queue full at Function.createLibrdkafkaError [as create] 
(/app/node_modules/node-rdkafka/lib/error.js:456:10) at Client._errorWrap 
(/app/node_modules/node-rdkafka/lib/client.js:481:29) at Producer.produce 
(/app/node_modules/node-rdkafka/lib/producer.js:138:15) at ProducerClient.produce 
```

**Comment by sotojn** [comment]
I think I've finally found the root cause of this error and have a proposed solution. The local Producer queue has two factors it checks for when determining if the queue is full.

- If the number of messages in the queue exceeds the number set at `queue.buffering.max.messages`
  - This situation seems to be handled properly in our own code. We prevent this from happening by always calling a `flush` on the queue after we've pushed the max allowed messages to the Producer queue. Below is the logic that does this:
  - https://github.com/terascope/kafka-assets/blob/3b59e9bbe6377e4aea0ef3c8a0eb58a2efd357fe/asset/src/_kafka_clients/producer-client.ts#L55-L93
- If the byte size of the queue exceeds what number is set at `queue.buffering.max.kbytes`
  - This isn't handled. By default, `queue.buffering.max.kbytes` is set to `1048576`. This has a high priority over `queue.buffering.max.messages`.
  - https://github.com/confluentinc/librdkafka/blob/master/CONFIGURATION.md

We need to handle the case where we run a kafka producer `flush` when we see that the next message we put into the queue will exceed the `queue.buffering.max.kbytes`.

**Comment by sotojn** [comment]
The easiest way to reproduce it is to lower the `queue.buffering.max.kbytes`. We don't use this configuration as of right now so pulling down the repo and adding it to the config below will work. 

Add this line:
```
'queue.buffering.max.kbytes': 10000,
```

Inside the `rdkafka_options` object here:
https://github.com/terascope/kafka-assets/blob/3b59e9bbe6377e4aea0ef3c8a0eb58a2efd357fe/asset/src/kafka_sender_api/api.ts#L46-L56

Then build the asset and upload it to a local teraslice cluster. Ensure you have standard assets uploaded as well and run this job:
```
{
    "name": "full kafka",
    "workers": 1,
    "lifecycle": "persistent",
    "assets": [
        "<Kafka hash goes here>",
        "standard"
    ],
    "apis": [
        {
            "_name": "kafka_sender_api",
            "topic": "test_topic",
            "wait": 500
        }
    ],
    "operations": [
        {
            "_op": "data_generator",
            "size": 40000
        },
        {
            "_op": "kafka_sender",
            "size": 40000,
            "api_name": "kafka_sender_api"
        }
    ]
}
```

Running this job will cause the `queue full` error because we exceeded the max kilobyte size on the producer queue even though we were 60k messages short of exceeding the max amount of messages.

Worker logs:
```
[2024-11-05T22:41:58.433Z] DEBUG: teraslice/9 on ts-wkr-full-kafka-3d62b88f-1775-5c4b96d68c-vhcsq: producing 40000 messages in batches 0... (assignment=worker, module=kafka-producer, worker_id=osa6bOto, ex_id=5fc5f903-aa3e-4893-bc92-914ec55d8aef, job_id=3d62b88f-1775-4996-9519-ae7b5b108f9f, opName=kafka_sender)
[2024-11-05T22:41:58.750Z] ERROR: teraslice/9 on ts-wkr-full-kafka-3d62b88f-1775-5c4b96d68c-vhcsq: (assignment=worker, module=worker_context, worker_id=osa6bOto, ex_id=5fc5f903-aa3e-4893-bc92-914ec55d8aef, job_id=3d62b88f-1775-4996-9519-ae7b5b108f9f, err.code=-184)
    A slice error occurred {
      slice: {
        slice_id: '9bff2e62-9f52-48aa-94ef-827f574838c2',
        slicer_id: 0,
        slicer_order: 1,
        request: { count: 40000, processed: 40000 },
        _created: '2024-11-05T22:41:53.536Z'
      }
    }
    --
    Error: Local: Queue full
        at Function.createLibrdkafkaError [as create] (/app/node_modules/node-rdkafka/lib/error.js:456:10)
        at Client._errorWrap (/app/node_modules/node-rdkafka/lib/client.js:500:29)
        at Producer.produce (/app/node_modules/node-rdkafka/lib/producer.js:138:15)
        at ProducerClient.produce (file:///app/assets/a603534d8f792b9d568bf1e1d91c1ba04b5b4695/index.js:19042:22)
        at KafkaSender.send (file:///app/assets/a603534d8f792b9d568bf1e1d91c1ba04b5b4695/index.js:19674:25)
        at KafkaSender2.onBatch (file:///app/assets/a603534d8f792b9d568bf1e1d91c1ba04b5b4695/index.js:19972:20)
        at KafkaSender2.handle (file:///app/assets/a603534d8f792b9d568bf1e1d91c1ba04b5b4695/index.js:17413:31)
        at file:///app/source/packages/job-components/dist/src/execution-context/worker.js:89:49
        at file:///app/source/packages/utils/dist/src/promises.js:215:16
        at async WorkerExecutionContext._runSliceOnce (file:///app/source/packages/job-components/dist/src/execution-context/worker.js:295:29)
        at async pRetry (file:///app/source/packages/utils/dist/src/promises.js:88:16)
        at async SliceExecution.run (file:///app/source/packages/teraslice/dist/src/lib/workers/worker/slice.js:38:22)
        at async Worker.runOnce (file:///app/source/packages/teraslice/dist/src/lib/workers/worker/index.js:169:13)
        at async _run (file:///app/source/packages/teraslice/dist/src/lib/workers/worker/index.js:124:17)
```
